version: '3.8'
services:
  payment_app:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - ./payment-service:/var/www/html
    depends_on:
      payment_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - APP_KEY=base64:YOUR_PAYMENT_APP_KEY
      - DB_HOST=payment_db
      - DB_DATABASE=payment_db
      - DB_USERNAME=user
      - DB_PASSWORD=secret
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=rabbitmq
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - RABBITMQ_QUEUE=corporate_request_queue
      - RABBITMQ_TIMEOUT=10
  corporate_app:
    build:
      context: ./corporate-service
      dockerfile: Dockerfile
    ports:
      - "8001:9000"
    volumes:
      - ./corporate-service:/var/www/html
    depends_on:
      corporate_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - APP_KEY=base64:YOUR_CORPORATE_APP_KEY
      - DB_HOST=corporate_db
      - DB_DATABASE=corporate_db
      - DB_USERNAME=user
      - DB_PASSWORD=secret
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=rabbitmq
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - RABBITMQ_QUEUE=corporate_request_queue
      - RABBITMQ_TIMEOUT=10
  payment_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
  corporate_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=corporate_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - corporate_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:6
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  payment_db_data:
  corporate_db_data: